---
dependencies:
  - geerlingguy.php

galaxy_info:
  role_name: php-mysql
  author: Laureh
  description: PHP MySQL support for Linux.
  company: "DSG"
  license: "license (Public)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database
    - web
    - mysql
    - php
