---
dependencies: []

galaxy_info:
  role_name: apache
  author: Laureh
  description: Apache 2.x for Linux.
  company: "DSG"
  license: "license (Public)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Solaris
      versions:
        - 11.3
  galaxy_tags:
    - web
    - apache
    - webserver
    - html
    - httpd

allow_duplicates: true
