---
galaxy_info:
  author: Laureh
  description: Prometheus node_exporter
  license: MPublic
  min_ansible_version: 2.1
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - networking
  - web
  - monitoring
